tasks:
  - init: bundle install # runs during prebuild
    command: budnle exec guard

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
