tasks:
  - init: bash -ic "bundle install" # runs during prebuild
    command: bash -ic "bundle exec guard"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
